### PR TITLE
Webpacker support

### PR DESCRIPTION
**Pull request by prem-prakash**
https://github.com/fphilipe/premailer-rails/issues/232

### CODE REVIEW

**Comment by olegsfinest** [comment]
Are there any plans to merge this?

**Comment by unRARed** [comment]
I'm surprised this support is not already available here given how long ago Rails moved to favor webpack for assets. Although it seems a lot of apps are using a mix of sprockets and webpack.

**Comment by prem-prakash** [comment]
@fphilipe any thoughts on this?

**Comment by unRARed** [comment]
I should mention this is not actually working for me so far, but it's likely I'm missing another part of the configuration.

**Comment by prem-prakash** [comment]
@unRARed I have really not used this code so I can't tell you. But I wish `premailer-rails` could support `webpacker` so I can use it for my incoming projects.

**Comment by prem-prakash** [comment]
closing because I could not move forward

**Pull request closed without merging**
