### PR TITLE
Add changelog to gemspec

### PR DESCRIPTION
**Pull request by rafbm**
For a nice “Changelog” link in the https://rubygems.org/gems/premailer-rails sidebar.

### CODE REVIEW

**Comment by fphilipe** [comment]
Thanks, that's a great idea!

I just checked other gems and they usually point to the changelog at the specific tag. Would you mind changing the value to this?

```ruby
"https://github.com/fphilipe/premailer-rails/blob/v#{Premailer::Rails::VERSION}/CHANGELOG.md"
```

**Comment by rafbm** [comment]
I’ve personally seen more gems link to their changelog on master and I think that makes for a better experience. It’s not impossible that some release notes someday will be incomplete (or just missing) and you’d want to update them after cutting the release. With a tagged link on https://rubygems.org/gems/premailer-rails the visitor would click and get the outdated, incomplete changelog.

Rails uses tagged links, but in their case it’s a [release link](https://github.com/rails/rails/releases/tag/v6.0.2.2) so they don’t have this problem; they can always edit the release’s notes afterwards.

Perhaps a middle ground would be to [link to master with an anchor to the version](https://github.com/fphilipe/premailer-rails/blob/master/CHANGELOG.md#v1111):

```ruby
"https://github.com/fphilipe/premailer-rails/blob/master/CHANGELOG.md#v#{Premailer::Rails::VERSION.delete('.')}"
```

Let me know what you prefer.

**Comment by fphilipe** [comment]
> Rails uses tagged links, but in their case it’s a release link so they don’t have this problem; they can always edit the release’s notes afterwards.

True, bot not for the dependencies such as [activesupport](https://rubygems.org/gems/activesupport), [activerecord](https://rubygems.org/gems/activerecord), etc.

I prefer it that way, if you don't mind 😊

**Comment by rafbm** [comment]
Alright, updated!

**Comment by fphilipe** [comment]
Thanks for your contribution! ❤️

**Pull request merged**
