### PR TITLE
remove any style links we are processing

### PR DESCRIPTION
**Pull request by mreinsch**
With this path I'm removing any style links prevailer-rails is already processing. This addresses #48.

### CODE REVIEW

**Comment by mreinsch** [comment]
BTW, we've been running with this patch in production for quite a while now...

**Comment by fphilipe** [comment]
I'm a bit outdated on the code. Maybe you can help me a bit here :blush: Can you explain to me why this is needed? Is it to prevent a further process of the stylesheet by premailer? Are there other reasons for doing this?

**Comment by mreinsch** [comment]
Sure. Without removing the stylesheet from the header, premailer will fetch the stylesheet once more. It seems there is an option to not have premailer load the stylesheet, but that isn't enabled by default. And previously I don't think that option was available. Anyway, removing the header seemed the easiest and cleanest way to just make sure that premailer will just use the styles already loaded by premailer-rails.

**Comment by mreinsch** [comment]
thanks! You can close https://github.com/fphilipe/premailer-rails/issues/48 now as well.

**Comment by fphilipe** [comment]
@mreinsch Thank you!

**Pull request merged**
